name: Docker Build ARM64 CUDA

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: arm-nvidia-runner-set
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        cuda-version: ["11.8.0"]
        platform: ["linux/arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          version: latest
          driver-opts: image=moby/buildkit:v0.19.0

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          BUILD_PLATFORMS: ${{ matrix.platform }}
          CUDA_VERSION: ${{ matrix.cuda-version }}
          DOCKER_REGISTRY: harbor.holdenitdown.net
          DOCKER_ORG: ops
        run: |
          make -f docker.Makefile




